#!/usr/bin/env node
/**
 * Token generator. Reads primitives.json + themes/*.json, resolves {a.b.c}
 * references, and emits one artifact per target runtime.
 *
 * Deliberately hand-rolled and dependency-free: it is smaller than the config
 * file a generic token pipeline would need, and it runs on bare `node`.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, '..', 'src');
const DIST = join(here, '..', 'dist');

const P = '--wk-'; // custom-property prefix. Namespaced so wertkit can be
                   // injected into a hostile page (browser extensions) safely.

const primitives = JSON.parse(readFileSync(join(SRC, 'primitives.json'), 'utf8'));
const themeFiles = readdirSync(join(SRC, 'themes')).filter((f) => f.endsWith('.json')).sort();
const themes = themeFiles.map((f) => JSON.parse(readFileSync(join(SRC, 'themes', f), 'utf8')));

/** Resolve "{color.slate.900}" against primitives. Throws on a dangling ref. */
function resolve(value, ctx) {
  if (typeof value !== 'string') return value;
  return value.replace(/\{([^}]+)\}/g, (_, path) => {
    const hit = path.split('.').reduce((acc, k) => (acc == null ? acc : acc[k]), primitives);
    if (hit === undefined) throw new Error(`unresolved token reference {${path}} in ${ctx}`);
    return hit;
  });
}

const roleEntries = (theme) =>
  Object.entries(theme)
    .filter(([k]) => !k.startsWith('$'))
    .map(([k, v]) => [k, resolve(v, theme.$name)]);

// Density + pointer-size scales. Control heights are the one axis that is
// painful to retrofit, so they live in tokens rather than in each component.
const CONTROL = {
  normal:  { sm: '28px', md: '36px', lg: '44px' },
  compact: { sm: '24px', md: '30px', lg: '36px' },
  coarse:  { sm: '36px', md: '44px', lg: '52px' }, // >=44px touch target (WCAG 2.5.5)
};

/* ---------------------------------------------------------------- CSS ---- */
function buildCss() {
  const L = [];
  L.push('/* GENERATED by @wertkit/tokens - do not edit. Run `pnpm -F @wertkit/tokens build`. */');
  L.push(':root {');
  for (const [k, v] of Object.entries(primitives.font))   L.push(`  ${P}font-${k}: ${v};`);
  for (const [k, v] of Object.entries(primitives.text)) {
    L.push(`  ${P}text-${k}: ${v.size};`);
    L.push(`  ${P}leading-${k}: ${v.line};`);
  }
  for (const [k, v] of Object.entries(primitives.weight)) L.push(`  ${P}weight-${k}: ${v};`);
  for (const [k, v] of Object.entries(primitives.space))  L.push(`  ${P}space-${k}: ${v};`);
  for (const [k, v] of Object.entries(primitives.radius)) L.push(`  ${P}radius-${k}: ${v};`);
  for (const [k, v] of Object.entries(primitives.border)) L.push(`  ${P}border-${k}: ${v};`);
  for (const [k, v] of Object.entries(primitives.shadow)) L.push(`  ${P}shadow-${k}: ${v};`);
  for (const [k, v] of Object.entries(primitives.tracking)) L.push(`  ${P}tracking-${k}: ${v};`);
  for (const [k, v] of Object.entries(primitives.motion)) L.push(`  ${P}motion-${k}: ${v};`);
  for (const [k, v] of Object.entries(primitives.z))      L.push(`  ${P}z-${k}: ${v};`);
  for (const [k, v] of Object.entries(CONTROL.normal))    L.push(`  ${P}control-h-${k}: ${v};`);
  L.push(`  ${P}control-px: var(${P}space-3);`);
  // Padding inside raised surfaces (dialogs, menus, cards). Generous by
  // default; the compact density pulls it back for data-dense views.
  L.push(`  ${P}surface-p: var(${P}space-6);`);
  L.push(`  ${P}cell-py: var(${P}space-3);`);
  L.push(`  ${P}focus-width: 2px;`);
  L.push(`  ${P}safe-t: env(safe-area-inset-top, 0px);`);
  L.push(`  ${P}safe-b: env(safe-area-inset-bottom, 0px);`);
  L.push(`  ${P}safe-l: env(safe-area-inset-left, 0px);`);
  L.push(`  ${P}safe-r: env(safe-area-inset-right, 0px);`);
  L.push(`  ${P}titlebar-h: 32px;`);
  L.push('}');
  L.push('');
  L.push('/* Touch devices get larger controls without any per-component change. */');
  L.push('@media (pointer: coarse) {');
  L.push('  :root {');
  for (const [k, v] of Object.entries(CONTROL.coarse)) L.push(`    ${P}control-h-${k}: ${v};`);
  L.push(`    ${P}control-px: var(${P}space-4);`);
  L.push('  }');
  L.push('}');
  L.push('');
  L.push('[data-density="compact"] {');
  for (const [k, v] of Object.entries(CONTROL.compact)) L.push(`  ${P}control-h-${k}: ${v};`);
  L.push(`  ${P}control-px: var(${P}space-2);`);
  L.push(`  ${P}surface-p: var(${P}space-4);`);
  L.push(`  ${P}cell-py: var(${P}space-2);`);
  L.push('}');
  L.push('');

  const emitRoles = (theme, selector, indent = '') => {
    L.push(`${indent}${selector} {`);
    L.push(`${indent}  color-scheme: ${theme.$colorScheme};`);
    for (const [k, v] of roleEntries(theme)) L.push(`${indent}  ${P}${k}: ${v};`);
    L.push(`${indent}}`);
  };

  const light = themes.find((t) => t.$name === 'light');
  const dark = themes.find((t) => t.$name === 'dark');

  L.push('/* Default: light, unless the OS asks for dark and no theme is pinned. */');
  emitRoles(light, ':root');
  L.push('');
  L.push('@media (prefers-color-scheme: dark) {');
  emitRoles(dark, ':root:not([data-theme])', '  ');
  L.push('}');
  L.push('');
  for (const t of themes) {
    emitRoles(t, `[data-theme="${t.$name}"]`);
    L.push('');
  }
  L.push('@media (prefers-reduced-motion: reduce) {');
  L.push('  :root {');
  L.push(`    ${P}motion-fast: 1ms;`);
  L.push(`    ${P}motion-base: 1ms;`);
  L.push('  }');
  L.push('}');
  return L.join('\n') + '\n';
}

/* ----------------------------------------------------------------- TS ---- */
function buildTs() {
  const themeObj = {};
  for (const t of themes) themeObj[t.$name] = Object.fromEntries(roleEntries(t));
  const names = themes.map((t) => t.$name);
  return `// GENERATED by @wertkit/tokens - do not edit.
// Plain values, no CSS dependency, so a future React Native target can consume
// the same source of truth.

export const themeNames = ${JSON.stringify(names)} as const;
export type ThemeName = (typeof themeNames)[number];

export const densities = ['normal', 'compact'] as const;
export type Density = (typeof densities)[number];

export const themes = ${JSON.stringify(themeObj, null, 2)} as const;
export type ColorRole = keyof (typeof themes)['light'];

export const space = ${JSON.stringify(primitives.space, null, 2)} as const;
export const radius = ${JSON.stringify(primitives.radius, null, 2)} as const;
export const text = ${JSON.stringify(primitives.text, null, 2)} as const;
export const weight = ${JSON.stringify(primitives.weight, null, 2)} as const;
export const font = ${JSON.stringify(primitives.font, null, 2)} as const;
export const motion = ${JSON.stringify(primitives.motion, null, 2)} as const;
export const tracking = ${JSON.stringify(primitives.tracking, null, 2)} as const;
export const control = ${JSON.stringify(CONTROL, null, 2)} as const;

/** CSS custom-property name for a colour role, e.g. cssVar('fg-muted'). */
export const cssVar = (role: ColorRole | string) => \`var(${P}\${role})\`;
`;
}

/* ---------------------------------------------------------------- Rust --- */
function buildRs() {
  const ident = (k) => k.replace(/-/g, '_');
  // Terminals: honour the user's own colour scheme by default. Truecolor hex is
  // available but must be opted into - overriding a user's terminal theme is a
  // bug, not a feature.
  const ANSI = {
    fg: 'Reset', 'fg-muted': 'BrightBlack', 'fg-subtle': 'BrightBlack',
    bg: 'Reset', 'bg-subtle': 'Reset', 'bg-raised': 'Reset', 'bg-inset': 'Reset',
    border: 'BrightBlack', 'border-strong': 'White', 'focus-ring': 'Cyan',
    accent: 'Cyan', 'accent-hover': 'BrightCyan', 'accent-fg': 'Black', 'accent-subtle': 'Reset',
    danger: 'Red', 'danger-fg': 'BrightRed', 'danger-subtle': 'Reset',
    warn: 'Yellow', 'warn-fg': 'BrightYellow', 'warn-subtle': 'Reset',
    success: 'Green', 'success-fg': 'BrightGreen', 'success-subtle': 'Reset',
    info: 'Blue', 'info-fg': 'BrightBlue', 'info-subtle': 'Reset',
    overlay: 'Reset',
  };
  const roles = roleEntries(themes.find((t) => t.$name === 'light')).map(([k]) => k);
  const L = [];
  L.push('// GENERATED by @wertkit/tokens - do not edit.');
  L.push('');
  L.push('#[derive(Debug, Clone, Copy)]');
  L.push('pub struct Theme {');
  for (const r of roles) L.push(`    pub ${ident(r)}: &'static str,`);
  L.push('}');
  L.push('');
  for (const t of themes) {
    L.push(`pub const ${t.$name.toUpperCase()}: Theme = Theme {`);
    for (const [k, v] of roleEntries(t)) L.push(`    ${ident(k)}: "${v}",`);
    L.push('};');
    L.push('');
  }
  L.push('/// ANSI-16 fallback. Prefer this in a TUI: it respects whatever palette');
  L.push('/// the user configured in their terminal instead of overriding it.');
  L.push('#[derive(Debug, Clone, Copy)]');
  L.push('pub enum Ansi {');
  L.push('    Reset, Black, Red, Green, Yellow, Blue, Magenta, Cyan, White,');
  L.push('    BrightBlack, BrightRed, BrightGreen, BrightYellow, BrightBlue,');
  L.push('    BrightMagenta, BrightCyan, BrightWhite,');
  L.push('}');
  L.push('');
  L.push('pub const fn ansi(role: &str) -> Ansi {');
  L.push('    match role.as_bytes() {');
  for (const r of roles) L.push(`        b"${r}" => Ansi::${ANSI[r] ?? 'Reset'},`);
  L.push('        _ => Ansi::Reset,');
  L.push('    }');
  L.push('}');
  L.push('');
  L.push('pub mod space {');
  for (const [k, v] of Object.entries(primitives.space)) {
    L.push(`    pub const S${k}: u16 = ${parseInt(v, 10) || 0};`);
  }
  L.push('}');
  return L.join('\n') + '\n';
}

mkdirSync(DIST, { recursive: true });
writeFileSync(join(DIST, 'tokens.css'), buildCss());
writeFileSync(join(DIST, 'tokens.ts'), buildTs());
writeFileSync(join(DIST, 'tokens.rs'), buildRs());
console.log(
  `wertkit tokens: ${themes.length} themes (${themes.map((t) => t.$name).join(', ')}) ` +
  `-> tokens.css, tokens.ts, tokens.rs`
);
